"""Helpers for interacting with databases."""

import typing as t


def execute(con, sql: str, args: tuple = ()) -> int | None:
    """Execute an SQL statement.

    Args:
        con: connection object
        sql: the statement to execute
        args: arguments to interpolate into the statement

    Returns:
        The value of `lastrowid`, usually an autogenerated primary key.
    """
    cur = con.cursor()
    cur.arraysize = 50
    try:
        cur.execute(sql, args)
        result = cur.lastrowid
        con.commit()
        return result
    finally:
        cur.close()


def query(con, sql: str, args: tuple = ()) -> t.Iterator[dict]:
    """Run an SQL query.

    Args:
        con: connection object
        sql: the statement to execute
        args: arguments to interpolate into the statement

    Yields:
        The rows of the result.
    """
    cur = con.cursor()
    try:
        cur.execute(sql, args)
        yield from iter(cur.fetchone, None)
    finally:
        cur.close()


def query_row(con, sql: str, args: tuple = (), *, default=None) -> dict | None:
    """Run an SQL query expected to return a single row.

    Args:
        con: connection object
        sql: the statement to execute
        args: arguments to interpolate into the statement
        default: value to return if no rows are returned by the query

    Returns:
        The matched row.
    """

    cur = con.cursor()
    try:
        cur.execute(sql, args)
        for row in iter(cur.fetchone, None):
            return row
    finally:
        cur.close()
    return default


def query_value(
    con,
    sql: str,
    args: tuple = (),
    *,
    default: int | str | None = None,
) -> int | str | None:
    """Run an SQL query expected to return a single value.

    Args:
        con: connection object
        sql: the statement to execute
        args: arguments to interpolate into the statement
        default: value to return if no rows are returned by the query

    Returns:
        The first field of the matched row.
    """
    cur = con.cursor()
    try:
        cur.execute(sql, args)
        for row in iter(cur.fetchone, None):
            return row[0]
    finally:
        cur.close()
    return default
